@startuml

start
:definicje zmiennych, gdzie te zmienne przechowują informacje które potem
funkcja "pobierz_dane()" - urzyje do wygenerowania schemtu;
:utworzenie okna GUI - root = tk.Tk() - narazie puste , potem dochadzą elementy ;
:utworzenie trzech przycisków radiowych - odnoisnie rodzaju zabezpieczdnia głównego
w pętli for , z iteracja po liscie opcje;
:ustawnienie wartości początkowej,
"typ S - C 3polowe";
:utworzenie dwuch przycisków radiowych - odnosnie podzespołów
w pętli for , z iteracja po liscie opcje2;
:ustawienie wartości początkowej:
"tylko łącznik tyrystorowy i 3 dlawiki";
stop


start
:pobierz_dane()
opis działania funkcji;
:BLOK - pobierz_dane - przypisywanie do zmiennych od podzespoly

do zmiennych d1...d3 , s4...s15 przypisujemy wartości podzespołów
mozliwe braki wartości, wtedy zmienna przechowuje pusty string -> "";
switch( opcja - dodatkowe stopnie)
case(  zmienna podzespoly_dodatkowe == "tylko łącznik tyrystorowy i 3 dlawiki")
:BLOK - pobierz_dane - brak dodatkowych podzespolow

Jest wybrane w GUI :
"tylko łącznik tyrystorowy i 3 dlawiki";
switch(zmienna zab_zew == )
case()
:typ S - C 3polowe;
:generowanie grafiki i zapis ;
case()
:wkladki topikowe gG;
:generowanie grafiki i zapis ;
case()
:brak zabezpieczenia glownego;
:generowanie grafiki i zapis ;
endswitch
case(  zmienna podzespoly_dodatkoe == "dodatkowe stopnie"\n  zmienna zab_zew = "typ S - C 3polowe")
:BLOK - pobierz_dane - dodatkowe stopnie

Jest wybrane w GUI -> dodatkowe stopnie;
    switch(if ilosc_stopni <= 6 \n )
        case( if ilosc-stopni <= 6 : \n BLOK - pobierz_dane - dodatkowe stopnie -> \n generowanie grafiki z dodatkowymi stopniami )

            :otiweramy grafikę z schematem głównym , gdzie są sciezki na dodatkowe podzespoły

               jest do wyboru 6 grafik - zalezne od ilości stopni;
               note left
                :kiedyś będzie więcej grafik;
                endnote
            :utworzenie zmiennej :
            szerokosc_wstawianie_sciezki

            dzieki tej zmiennej - wstawiane grafiki będą mogły być przesuwane w prawo,
            gdyz zawsze jest dodawana wartośś szerokosci;
            :utworzenie zmiennej:
            ilosc_umieszczonych_stopni

            zmienna rpzsnie o +1 z kazdym dodaniem kolejnego stopnia -
            dzięki temu możemy podczas ładowania grafik "Q4....Q10"
            załadować odpowiednią - w sciezce do grafiki podmieniamy wartosc zmiennej
            ;
            :
            utworzenie zmiennej:
            nazwa_pliku

            będą generowane grafiki z tekstem - z wartosciami stopni
            ;
                switch()
                    case()
                        :jednofazowe;
                        note left
                        do poprawy dla jedno fazowych i trzyfazowych
                        zrobic licznik stopni zeby Q1....Qn - było liczone
                        endnote
                        :if i == 0
                        - otwarcie grafiki z podlaczeniem stopnia
                        - umiejscowienie tej grafiki
                        - otwarcie grafiki od kondensatora badz dławika
                        - umiejscowienie tej grafiki
                        - otwarcie grafiki od stopnia
                        - umiejscowienie tej grafiki
                        -
                        ;
                    case()
                        :trzyfazowe;
                endswitch
        case( else : \n BLOK - pobierz_dane - dodatkowe stopnie -> \n nie generujemy schematu , wyswietlamy komunikat )
            :
            Nie możemy wygenerować grafik, bo liczba dodatkowych stopni przekroczyła 6
            na razie nie program jest w wersji podstawowej,

            Wyświetlamy komunikat :
            "Przekroczono ilosc stopni , aplikacja pozwala na max 6";


endswitch


endswitch
stop

@enduml
